### ISSUE TITLE
[Rgs] Port the 'roles' cog

### ISSUE THREAD

**Issue by sinus-x** [pumpkin-py/pumpkin-management#10]
Port the [roles cog](https://github.com/sinus-x/rubbergoddess/tree/master/cogs/roles) to this pumpkin.py repository into 'channels' module.

Required changes:
- New pumpkin.py translation system is used
- pumpkin.py database scheme is used
- Use Pythonic names
- Drop the role comparisons. Each reaction channel can be enabled in TextChannel or Role mode: for TextChannel only channel overwrites can be altered, for Role channel only roles can be altered. These channels are write-protected, the role height has been kept there for historical reasons.
- API calls should be kept as low as possible at to prevent rate limiting

Feel free to reach out for clarification.

**Comment by ArcasCZ** [comment]
I'm on it. I'm gonna use Views and buttons for this.

![image](https://user-images.githubusercontent.com/6602975/144753216-ee545517-7dbd-42df-a400-981780b17c86.png)

**Comment by sinus-x** [comment]
Done in #33
