### ISSUE TITLE
Command to change member's verification status

### ISSUE THREAD

**Issue by sinus-x** [pumpkin-py/pumpkin-management#34]
We have no way of changing the verification status (e.g. VERIFIED -> BANNED) at the moment.

**Comment by JawadHalabiMTB** [comment]
@sinus-x Hi, I see there is a function "dump" under database.py which fits your request doesn't it ?

**Comment by sinus-x** [comment]
@JawadHalabiMTB Hi, no, unfortunately it's not that easy. I just found out that we already have some kind of function like that, it was on different place from where I was looking for it -- which means I'm closing this issue as it is invalid.

However, if you want to contribute to our project, feel free to find another issue in any of our repositories. If you'd like to contribute, make sure you can run the bot instance locally (see [the docs](pumpkinpy.readthedocs.io)) and understand the basics of installing bot modules (`repo install` command).

**Comment by JawadHalabiMTB** [comment]
@sinus-x Thanks man appreciate it
